// parameters for testing sarek pipeline

input: "/scratch/users/szhuk/hpc_run/workspace/LD12_sample.csv"
outdir: "./results-sarek-test"
genome: "GRCh38"
igenomes_base: "/kuttam_fg/refdata/zhuk/iGenomes/"
wes: true
intervals: "/kuttam_fg/refdata/zhuk/Probes/ATX_screen.subset.bed"
joint_germline: false
tools: "haplotypecaller"